import type { Metadata } from "next";
import '@fontsource/inter';
import { Inter, Jersey_10 } from 'next/font/google';
import "./globals.css";
import PageTrans from "@/components/page-trans";

const inter = Inter({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

const jersey10 = Jersey_10({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <PageTrans>{children}</PageTrans>
      </body>
    </html>
  );
}
